import type { Metadata } from "next";
import "./globals.css";
import { inter, montserrat } from "./ui/fonts";
import { SideBarProvider } from "@/context/SideBarContext";
import { SideBar } from "@/components/NavBar/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SideBarProvider>
            <div className="flex min-h-screen">
              <SideBar />

              <main className="flex-1 bg-gray-100">
                {children}
              </main>
            </div>
        </SideBarProvider>
      </body>
    </html>
  );
}