import type { Metadata } from "next";
import "./globals.css";
import { inter, montserrat } from "./ui/fonts";
import { SideBarProvider } from "@/context/SideBarContext";
import { SideBar } from "@/components/NavBar/SideBar";
import { FileProvider } from "@/context/fileContext";
import { LayoutContent } from "./LayoutContent";

export const metadata: Metadata = {
  title: "StudyApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SideBarProvider>
          <LayoutContent>
            <FileProvider>
              {children}
            </FileProvider>
          </LayoutContent>
        </SideBarProvider>
      </body>
    </html>
  );
}